<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="LiteBus.Commands.Extensions.Microsoft.DependencyInjection" Version="5.0.0" />
    <PackageReference Include="LiteBus.Events.Extensions.Microsoft.DependencyInjection" Version="5.0.0" />
    <PackageReference Include="LiteBus.Queries.Extensions.Microsoft.DependencyInjection" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Demo.Domain\Demo.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Login\" />
  </ItemGroup>

</Project>
