version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: stress-test-gb-mysql
    environment:
      MYSQL_DATABASE: stress-test-gb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'      
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - stress-test-gb:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: stress-test-gb-redis
    ports:
      - 6379:6379

volumes:
  stress-test-gb:
