apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-exporter
  name: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-exporter
    spec:
      containers:
        - args:
            - --config.my-cnf=/cfg/.my.cnf
            - --mysqld.address=mysql:3306
          image: bitnami/mysqld-exporter:latest
          name: mysql-exporter
          ports:
            - containerPort: 9104
          resources: {}
          volumeMounts:
            - mountPath: /cfg/.my.cnf
              name: mysql-exporter-claim0
      restartPolicy: Always
      volumes:
        - name: mysql-exporter-claim0
          persistentVolumeClaim:
            claimName: mysql-exporter-claim0
status: {}
