# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.0.2

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
spec:
  selector:
    app.kubernetes.io/name: MySql
  containers:
  - name: mysql-container
    image: docker.io/library/mysql:latest
    ports:
    - containerPort: 3306
      hostPort: 3306  
  volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
  - args:
    - mysqld
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: '1234'    
  volumes:
  - name: mysql-data
    hostPath:
      path: /home/jgkim/k8s/mysql
      type: DirectoryOrCreate
