apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nexus
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nexus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: nexus
    spec:
      containers:
        - image: sonatype/nexus3:latest
          name: nexus
          ports:
            - containerPort: 8081
            - containerPort: 8082
          resources: {}
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus-claim0
      restartPolicy: Always
      volumes:
        - name: nexus-claim0
          persistentVolumeClaim:
            claimName: nexus-claim0
status: {}
