apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-mysql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/user/test-mysql"
