apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-exporter
  name: redis-exporter
spec:
  ports:
    - name: "9121"
      port: 9121
      targetPort: 9121
  selector:
    io.kompose.service: redis-exporter
status:
  loadBalancer: {}
