# OpenTelemetry Collector 프로덕션 환경 구성
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size: 4194304
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 2s
    send_batch_size: 2048
    send_batch_max_size: 4096

  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128

  resource:
    attributes:
      - key: service.name
        value: gamepulse
        action: upsert
      - key: deployment.environment
        value: production
        action: upsert
      - key: service.version
        value: ${SERVICE_VERSION}
        action: upsert

  # 프로덕션에서는 샘플링 적용
  probabilistic_sampler:
    sampling_percentage: 10.0

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    timeout: 30s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 60s
      max_elapsed_time: 300s

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      attributes:
        service.name: "service_name"
        level: "level"
        environment: "environment"

  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [loki]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, probabilistic_sampler, batch]
      exporters: [jaeger]

  telemetry:
    logs:
      level: warn
    metrics:
      address: 0.0.0.0:8888