# OpenTelemetry Collector Docker 환경용 구성 파일
# ECS 태스크에서 사이드카 컨테이너로 실행될 때 사용

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  memory_limiter:
    limit_mib: 256
    spike_limit_mib: 64

  resource:
    attributes:
      - key: service.name
        value: gamepulse
        action: upsert
      - key: deployment.environment
        value: production
        action: upsert

exporters:
  # Prometheus 메트릭 익스포터
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    timeout: 30s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s

  # Loki 로그 익스포터
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      attributes:
        service.name: "service_name"
        level: "level"
      resource:
        container.name: "container_name"

  # Jaeger 트레이스 익스포터
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [loki]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [jaeger]

  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888