# OpenTelemetry Collector 스테이징 환경 구성
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 512

  memory_limiter:
    limit_mib: 256
    spike_limit_mib: 64

  resource:
    attributes:
      - key: service.name
        value: gamepulse
        action: upsert
      - key: deployment.environment
        value: staging
        action: upsert
      - key: service.version
        value: ${SERVICE_VERSION}
        action: upsert

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    timeout: 30s

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      attributes:
        service.name: "service_name"
        level: "level"
        environment: "environment"

  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  # 스테이징에서는 로깅 익스포터도 활성화
  logging:
    loglevel: debug

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheusremotewrite, logging]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [loki, logging]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [jaeger, logging]

  telemetry:
    logs:
      level: debug
    metrics:
      address: 0.0.0.0:8888