# 파일 규격 버전
version: "3.7"
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services:
  rabbitmq:    
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1234
    volumes:
      - ./rabbitmq/lib:/var/lib/rabbitmq/'
      - ./rabbitmq/log:/var/log/rabbitmq/'
  # 서비스 명
  mysql:
    # 사용할 이미지
    image: mysql:8.4.0    
    # 컨테이너 이름 설정
    container_name: mysql
    restart: always
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "3306:3306"
    # -e 옵션 
    environment:
      MYSQL_DATABASE: test-db
      # MYSQL 패스워드 설정 옵션
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_ROOT_HOST: '%'
    # 명령어 실행 (한글 인코딩 관련)
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      # -v 옵션 (다렉토리 마운트 설정)
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/mysql.conf:/etc/mysql.conf.d/mysqld.cnf
  # redis
  redis:
    image: redis:bookworm
    container_name: redis    
    restart: always
    command: redis-server --port 6379
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
      - 6380:6379
    volumes:
      - ./redis/data:/data
  # InfluxDB - Database for sensor data
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/etc:/etc/influxdb2'
      - ./influxdb/lib:/var/lib/influxdb2'
  # prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  # grapana
  grapana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "1000:1000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
