version: "3.7"

services:
  # rabbitmq
  rabbitmq:    
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1234
    volumes:
      - ./rabbitmq/lib:/var/lib/rabbitmq/'
      - ./rabbitmq/log:/var/log/rabbitmq/'
  # mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test-db
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_ROOT_HOST: '%'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/mysql.conf:/etc/mysql.conf.d/mysqld.cnf
  # mysql-exporter
  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    restart: always
    ports: 
      - "9104:9104"
    command: 
      #- —mysqld.username=exporter:qwer34##$$
      - --config.my-cnf=/cfg/.my.cnf
      - --mysqld.address=mysql:3306
    volumes:
      - "./mysqlexporter/.my.cnf:/cfg/.my.cnf"
    links:
      - mysql
    depends_on:
      - mysql    
  # redis
  redis:
    image: redis:bookworm
    container_name: redis
    restart: always
    command: "--requirepass 1234"
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
      - 6380:6379
    volumes:
      - ./redis/data:/data    
  # redis prometheus exporter
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    restart: always
    ports:
      - 9121:9121
    command:
      - '--redis.addr=redis://redis:6379'
      - '--redis.password=1234'
    links:
      - redis
      - prometheus
  # InfluxDB - Database for sensor data
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/etc:/etc/influxdb2'
      - ./influxdb/lib:/var/lib/influxdb2'
  # prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  # grapana
  grapana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "1000:1000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
