# 파일 규격 버전
version: "3.7"
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services:
  RabbitMq:    
    image: rabbitmq:management
    container_name: rabbitmq    
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1234
    networks:
      app1_container_network:
        ipv4_address: 172.20.0.1
    volumes:
      - 'rabbitmq_lib:/var/lib/rabbitmq/'
      - 'rabbitmq_log:/var/log/rabbitmq/'
  # 서비스 명
  MySql:
    # 사용할 이미지
    image: mysql:8.1.0
    # 컨테이너 이름 설정
    container_name: mysql
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "3306:3306"
    # -e 옵션 
    environment:
      MYSQL_DATABASE: test-db
      # MYSQL 패스워드 설정 옵션
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_ROOT_HOST: '%'
    # 명령어 실행 (한글 인코딩 관련)
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      app1_container_network:
        ipv4_address: 172.20.0.2
    volumes:
      # -v 옵션 (다렉토리 마운트 설정)
      - 'mysql_lib:/var/lib/mysql'
  # redis
  Redis:
    image: redis:bookworm
    container_name: redis    
    command: redis-server --port 6379
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 16379:6379
      - 16380:6379
    networks:
      app1_container_network:
        ipv4_address: 172.20.0.3
    volumes:
      - 'redis_data:/data'
  # InfluxDB - Database for sensor data
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8086:8086"
    networks:
      app1_container_network:
        ipv4_address: 172.20.0.4
    volumes:
      - 'influxdb2_etc:/etc/influxdb2'
      - 'influxdb2_lib:/var/lib/influxdb2'
  # grapana
  grapana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000:1000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    networks:
      app1_container_network:
        ipv4_address: 172.20.0.5
    volumes:
      - 'grafana_storage:/var/lib/grafana'
      - ./grafana:/etc/grafana/provisioning/datasources
  # prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      app1_container_network:
        ipv4_address: 172.20.0.6
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  app1_container_network:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"

volumes:
  prometheus_data: {}
  rabbitmq_lib: {}
  rabbitmq_log: {}
  mysql_lib: {}
  redis_data: {}
  influxdb2_etc: {}
  influxdb2_lib: {}
  grafana_storage: {}
