version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "gamepulse-app"
          ContainerPort: 8080
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - "subnet-xxxxxxxxx"  # Private subnet 1
              - "subnet-yyyyyyyyy"  # Private subnet 2
            SecurityGroups:
              - "sg-zzzzzzzzz"      # ECS security group
            AssignPublicIp: "DISABLED"

Hooks:
  - BeforeInstall:
      - Location: scripts/before_install.sh
        Timeout: 300
        RunAs: root
  - AfterInstall:
      - Location: scripts/after_install.sh
        Timeout: 300
        RunAs: root
  - ApplicationStart:
      - Location: scripts/application_start.sh
        Timeout: 300
        RunAs: root
  - ApplicationStop:
      - Location: scripts/application_stop.sh
        Timeout: 300
        RunAs: root
  - BeforeAllowTraffic:
      - Location: scripts/before_allow_traffic.sh
        Timeout: 300
        RunAs: root
  - AfterAllowTraffic:
      - Location: scripts/after_allow_traffic.sh
        Timeout: 300
        RunAs: root